development:
  adapter: postgresql
  encoding: utf8
  database: krobnson
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: krobnson
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: kobnson
  pool: 5
  username:
  password:

cucumber:
  <<: *TEST
